---
kind: pipeline
name: rancher-deploy

steps:
  - name: rancher-deploy
    image: uala/drone-rancher-deploy
    settings:
      config: k8s-envs.yml
      dry_run: true
    environment:
      RANCHER_ACCESS_KEY:
        from_secret: RANCHER_ACCESS_KEY
      RANCHER_SECRET_KEY:
        from_secret: RANCHER_SECRET_KEY

---
kind: pipeline
name: deploy-after-test

steps:
  - name: deploy
    image: busybox
    commands:
      - echo "Hello World"
      - env

# When in master, develop or tags it will deploy only after test completion
trigger:
  branch:
   - master
   - develop
  event:
    - tag

---
kind: pipeline
name: deploy-with-test

steps:
  - name: deploy
    image: busybox
    environment:
      RANCHER_ACCESS_KEY:
        from_secret: RANCHER_ACCESS_KEY
      RANCHER_SECRET_KEY:
        from_secret: RANCHER_SECRET_KEY
      RANCHER_ACCESS_KEY_ENV:
        from_secret: RANCHER_ACCESS_KEY
      RANCHER_SECRET_KEY_ENV:
        from_secret: RANCHER_SECRET_KEY
    commands:
      - echo "Hello World"
      - env

# When in master, develop or tags it will deploy only after test completion
trigger:
  branch:
    exclude:
      - master
      - develop
  event:
    exclude:
      - tag

---
kind: pipeline
name: notify-pipeline-end

steps:
  - name: notify
    image: busybox
    commands:
      - echo "Sending notification"

depends_on:
  - deploy-with-test
  - deploy-after-test
