---
kind: pipeline
name: deploy-after-test

steps:
  - name: deploy
    image: busybox
    commands:
      - echo "Hello World"

# When in master, develop or tags it will deploy only after test completion
trigger:
  branch:
   - master
   - develop
  event:
    - tag

---
kind: pipeline
name: deploy-with-test

steps:
  - name: deploy
    image: busybox
    commands:
      - echo "Hello World"

---
kind: pipeline
name: notify-pipeline-end

steps:
  - name: notify
    image: busybox
    commands:
      - echo "Sending notification"

depends_on:
  - deploy-with-test
  - deploy-after-test
