---
kind: pipeline
name: rancher-deploy

steps:
  - name: Check tag is on master
    image: uala/drone-rancher-deploy
    settings:
      action: tag_check
      enforce_branch_for_tag: master
      fetch: true
      logging: debug
    when:
      event:
        - tag
  - name: rancher-deploy
    image: uala/drone-rancher-deploy
    settings:
      config: k8s-envs.yml
      dry_run: true
    environment:
      RANCHER_ACCESS_KEY:
        from_secret: RANCHER_ACCESS_KEY
      RANCHER_SECRET_KEY:
        from_secret: RANCHER_SECRET_KEY
