---
kind: pipeline
name: notify-pipeline-start

steps:
  - name: slack
    image: busybox
    commands:
      - echo "Hello World"

---
kind: pipeline
name: build-docker-image

steps:
  - name: docker-build-backend
    image: plugins/docker
    settings:
      repo: fabn/drone
      tags: latest
      cache_from:
        - "fabn/drone:latest"
        - "fabn/drone:${DRONE_SOURCE_BRANCH}"
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

---
kind: pipeline
name: rspec

steps:
  - name: rspec parallel
    image: fabn/drone:${DRONE_SOURCE_BRANCH}
    commands:
      - cd /app
      - cat current-date.txt

depends_on:
  - build-docker-image

---
kind: pipeline
name: rubocop

steps:
  - name: rubocop parallel
    image: fabn/drone:${DRONE_SOURCE_BRANCH}
    environment:
      RAILS_ENV: test
    commands:
      - cd /app
      - env
      - echo $RAILS_ENV
      - pwd
      - ls

depends_on:
  - build-docker-image
  
---
kind: pipeline
name: rancher-deploy

steps:
  - name: Feature Deploy ${DRONE_SOURCE_BRANCH}
    image: busybox
    commands:
      - echo "Deploying feature on xxx"
depends_on:
  - build-docker-image

# When in feature branches deploy without waiting for tests
trigger:
  branch:
    exclude:
      - master
      - develop
  event:
    exclude:
      - tag

---
kind: pipeline
name: rancher-deploy

steps:
  - name: ENV Deploy ${DRONE_SOURCE_BRANCH}
    image: busybox
    commands:
      - echo "Deploying on xxx after tests"

depends_on:
  - rubocop
  - rspec

# When in master, develop or tags it will deploy only after test completion
trigger:
  branch:
   - master
   - develop
  event:
    - tag

---
kind: pipeline
name: notify-pipeline-end

steps:
  - name: dump-env
    image: busybox
    commands:
      - echo "Hello World"

depends_on:
  - rubocop
  - rspec
  - rancher-deploy

trigger:
  status:
    - success
    - failure

