---
kind: pipeline
name: rancher-deploy

steps:
  - name: Fetch full git repo
    image: docker:git
    commands:
      - env
      - git fetch --all
  - name: Check tag is on master
    image: uala/drone-rancher-deploy
    settings:
      action: tag_check
      enforce_branch_for_tag: master
    when:
      event:
        - tag
  - name: Dump git environment
    image: docker:git
    commands:
      - env
      - ls -la .git
      - git remote -v
      - git rev-parse --abbrev-ref HEAD
      - git branch -a
      - git describe --all
  - name: rancher-deploy
    image: uala/drone-rancher-deploy
    settings:
      config: k8s-envs.yml
      dry_run: true
    environment:
      RANCHER_ACCESS_KEY:
        from_secret: RANCHER_ACCESS_KEY
      RANCHER_SECRET_KEY:
        from_secret: RANCHER_SECRET_KEY
